formatVersion: 1
inputs:
  user:
    type: string
    title: Username for SSH
    description: The username you would like to have for the installation.
    default: demouser
  password:
    type: string
    pattern: '[a-z0-9A-Z@#$]+'
    encrypted: true
    title: Admin Account Password
    description: The password you would like to use for the System.
resources:
  Salt-Minion:
    type: Cloud.Machine
    dependsOn:
      - Salt-Master
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      image: CentOS7.6
      flavor: Small
      customizationSpec: Linux
      cloudConfig: |
        #cloud-config
        users:
            name: ${input.user}
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
        runcmd:
          - PASS=${input.password}
          - USER=${input.user}
          - echo $USER:$PASS | /usr/sbin/chpasswd
          - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
          - systemctl reload sshd
          - cd /tmp
          - curl -O https://raw.githubusercontent.com/ahugla/CAS_vRA8/master/blueprints/Saltstack/Salt_Server_and_minion/salt_minion_install.sh
          - chmod 755 salt_minion_install.sh
          - ./salt_minion_install.sh ${resource.Salt-Master.address}
          - rm -f salt_minion_install.sh
      networks:
        - network: '${resource.Cloud_Network_1.id}'
          assignment: static
  Salt-Master:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 0
        - 1
    properties:
      image: CentOS7.6
      flavor: Small
      customizationSpec: Linux
      cloudConfig: |
        #cloud-config
        users:
          - name: ${input.user}
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
        runcmd:
          - PASS=${input.password}
          - USER=${input.user}
          - echo $USER:$PASS | /usr/sbin/chpasswd
          - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
          - systemctl reload sshd
          - cd /tmp
          - curl -O https://raw.githubusercontent.com/ahugla/CAS_vRA8/master/blueprints/Saltstack/Salt_Server_and_minion/salt_master_install.sh
          - chmod 755 salt_master_install.sh
          - ./salt_master_install.sh
          - rm -f salt_master_install.sh
      networks:
        - network: '${resource.Cloud_Network_1.id}'
          assignment: static
  Cloud_Network_1:
    type: Cloud.Network
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      constraints:
        - tag: 'net:nsx'
      networkType: existing
