formatVersion: 1
inputs:
  NbreNode:
    type: integer
    default: 2
    title: Nombre de kubernetes nodes
    minimum: 0
    maximum: 4
  rootPasswd:
    type: string
    description: Password root (deja configuré dans le template) de la VM master K8S.
    title: Password configuré
    encrypted: true
  k8s_cluter_name:
    type: string
    title: Nom du cluster Kubernetes
    description: Nom du cluster Kubernetes souhaité
    default: kubernetes
  kubernetesVersion:
    type: string
    default: 1.21.1
    title: Kubernetes version
    oneOf:
      - title: 1.21.1
        const: 1.21.1
      - title: 1.19.3
        const: 1.19.3
      - title: 1.18.5
        const: 1.18.5
      - title: 1.17.8
        const: 1.17.8
      - title: 1.16.12
        const: 1.16.12
  RangeIP:
    type: string
    description: DOIT ETRE UNIQUE - Range IP qui sera utilisé dans Kubernetes avec le mode de service de type LoadBalancer
    default: 172.17.1.226-172.17.1.239
    title: IP range
  cadvisor_version:
    type: string
    description: 'Check versions here - "https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cadvisor"'
    title: cadvisor Version
    default: v0.36.0
    enum:
      - v0.36.0
      - v0.34.0
      - v0.31.0
  LIserver:
    type: string
    default: vrli.cpod-vrealize.az-fkd.cloud-garage.net
    title: Log Insight Server
  LIversion:
    type: string
    default: v8.4.0
    title: Version de Log Insight
resources:
  K8S_Master:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      image: CentOS7.6
      flavor: Medium # 2 vCPU
      resourceGroupName: From_vRA8
      customizationSpec: Linux
      networks:
        - network: '${resource.Cloud_Network.id}'
          assignment: static
      cloudConfig: |
        #cloud-config
        packages:
          - git
        runcmd:
          - touch /etc/cloud/cloud-init.disabled
          - cd /tmp
          - git clone https://github.com/ahugla/CAS_vRA8.git
          - cp /tmp/CAS_vRA8/blueprints/Kubernetes/K8S-prepare.sh /tmp/K8S-prepare.sh
          - cp /tmp/CAS_vRA8/blueprints/Kubernetes/K8S-MasterConfig.sh /tmp/K8S-MasterConfig.sh
          - chmod 755 K8S-prepare.sh K8S-MasterConfig.sh
          - /tmp/K8S-prepare.sh ${input.kubernetesVersion}
          - /tmp/K8S-MasterConfig.sh ${input.RangeIP} ${input.cadvisor_version} ${input.k8s_cluter_name}
          - rm -f K8S-prepare.sh
          - rm -f K8S-MasterConfig.sh
  K8S_Nodes:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 0
        - 1
    properties:
      image: CentOS7.6
      flavor: Medium # 2 vCPU
      count: '${input.NbreNode}'
      resourceGroupName: From_vRA8
      customizationSpec: Linux
      networks:
        - network: '${resource.Cloud_Network.id}'
          assignment: static
      cloudConfig: |
        #cloud-config
        packages:
          - git
        runcmd:
          - touch /etc/cloud/cloud-init.disabled    # evite d'executer cloud-init au reboot
          - echo "resource.K8S_Master.address = " ${resource.K8S_Master.address}                          # Recupere souvent l'IP flannel =>  NO OK
          - echo "resource.K8S_Master.networks.address = " ${resource.K8S_Master.networks.address}        # Tableau des IPs des vnics  =>  NO OK
          - echo "resource.K8S_Master.networks.address[0] = " ${resource.K8S_Master.networks.address[0]}  # Premiere IP  =>  OK
          - cd /tmp
          - git clone https://github.com/ahugla/CAS_vRA8.git
          - cp /tmp/CAS_vRA8/blueprints/Kubernetes/K8S-prepare.sh /tmp/K8S-prepare.sh
          - cp /tmp/CAS_vRA8/blueprints/Kubernetes/K8S-JoinCluster.sh /tmp/K8S-JoinCluster.sh
          - chmod 755 K8S-prepare.sh K8S-JoinCluster.sh
          - /tmp/K8S-prepare.sh ${input.kubernetesVersion}
          - /tmp/K8S-JoinCluster.sh ${resource.K8S_Master.networks.address[0]}  ${input.rootPasswd}   ${input.LIserver}   ${input.LIversion}
          - rm -f K8S-prepare.sh
          - rm -f K8S-JoinCluster.sh
  Cloud_Network:
    type: Cloud.Network
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      networkType: existing
      constraints:
        - tag: 'net:no_nsx'
