formatVersion: 1
inputs:
  vmname:
    type: string
    title: vmname
  username:
    type: string
    title: user
  password:
    type: string
    title: password
    encrypted: true
  color:
    type: string
    title: choose a color
    enum:
      - blue
      - yellow
      - red
      - green
      - purple
    default: red
resources:
  Cloud_Network_1:
    type: Cloud.Network
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      networkType: existing
  Cloud_Machine_1:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      flavor: small
      image: ubuntu
      cloudConfig: |
        #cloud-config
        preserve_hostname: false
        hostname: ${self.resourceName} #using vm name
        fqdn: ${self.resourceName}.cpod-vr.shwrfr.mooo.com
        ssh_pwauth: yes
        chpasswd:
          list: |
            ${input.username}:${input.password}
          expire: false
        users:
          - default
          - name: ${input.username}
            lock_passwd: false
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: [wheel, sudo, admin]
            shell: '/bin/bash'
        network:
          version: 2
          config:
            - type: physical
              name : ens192
              subnets:
                - type: static
                  addresses: ${resource.Cloud_Machine_1.networks.address[0]}/${resource.Cloud_Network_1.prefixLenght}
                  gateway: ${resource.Cloud_Network_1.gateway}
        runcmd:
          - echo "Defaults:${input.username}  !requiretty" >> /etc/sudoers.d/${input.username}
          - echo "selected color is ${input.color}" >> /tmp/color.txt
      networks:
        - network: '${resource.Cloud_Network_1.id}'
          assignment: static
